# Generated by Django 3.2.6 on 2023-03-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='updated_at',
        ),
    ]
