# Generated by Django 3.2.6 on 2023-03-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
