# Generated by Django 3.2.6 on 2023-03-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_review'),
        ('realm', '0002_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attending',
            field=models.ManyToManyField(blank=True, related_name='attending', to='events.Event'),
        ),
    ]
