# Generated by Django 3.2.6 on 2023-03-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0003_userprofile_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghost',
            name='encounters',
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
        migrations.DeleteModel(
            name='Ghost',
        ),
    ]
